### ISSUE TITLE
SSLv2 的 问题似乎没有得到解决

### ISSUE THREAD

**Issue by zambery** [Macr0phag3/ja3box#1]
SSLv2 的 问题似乎没有得到解决

这是工具返回的结果：
![image](https://user-images.githubusercontent.com/51513888/89172753-baeb4880-d5b5-11ea-9056-07a841c30cdd.png)

但是仔细观察pcap包可以发现它含有SSLv2 的client hello包
![image](https://user-images.githubusercontent.com/51513888/89172869-ec641400-d5b5-11ea-8b33-c85ae0dbd1ee.png)

**Comment by Macr0phag3** [comment]
发一下测试的网址吧~
@zambery

**Comment by Macr0phag3** [comment]
或者 pcap 数据包
@zambery

**Comment by zambery** [comment]
[192.168.0.67.pcap.zip](https://github.com/Macr0phag3/ja3box/files/5015450/192.168.0.67.pcap.zip)
这是测试包

**Comment by Macr0phag3** [comment]
问题找到了...明天我给修一下~
@zambery

**Comment by zambery** [comment]
可以先简单说明一下问题出在哪里了吗？我尝试添加`pkt.haslayer('SSLv2ClientHello')` 的判断条件，但是没有效果

**Comment by Macr0phag3** [comment]
就是没加 ssl 层，要加的话得看一下 scapy 的文档
@zambery

**Comment by zambery** [comment]
SSLv2、SSLv3、TLSv1、TLSv1.1这些都可以加进去吧，现在一些恶意流量还用的是老版本的协议，这个指纹加进去很有意义啊

**Comment by Macr0phag3** [comment]
嗯嗯，说起来你可能不信，我一直以为我加了 ssl...有时间的话会补上的~
@zambery

**Comment by zambery** [comment]
感谢开源，看了scapy文档，sslv2已经解决了，希望楼主能继续完善，(ง •_•)ง

**Comment by zambery** [comment]
发现一个小bug
这里的`Cipher = get_attr(TLSServerHello, 'ciphers')` ciphers 在ServerHello中应该是`Cipher = get_attr(TLSServerHello, 'cipher')`

**Comment by Macr0phag3** [comment]
1. 修复了 `Server Cipher` 的 bug
2. 升级了 ja3.py，现在应该支持全版本的 TLS/SSL 了

希望你能帮忙测试一下，谢谢！

@zambery
