### ISSUE TITLE
代码运行的一些问题

### ISSUE THREAD

**Issue by cmh14** [Macr0phag3/ja3box#2]
作者您好，我今天下午还没看代码具体细节，先试着运行了一下您这个ja3box的代码，发现一些情况想要和你交流一下
首先我发现我的colorama设置的那些颜色效果在pycharm直接运行和命令行里面结果不太一样，在pycharm的run里面正常对应了各种彩色，但是在terminal里面颜色都是0？m32类似这样的情况。第二个是好像您设置的json存储时候只存储了ja3s而没有存ja3，看您提供的test.json也是这个样子

**Comment by cmh14** [comment]
还有个更加奇怪的问题，命令行中Client和Server hello的消息都可以正常打印，但是最终那个Client 和Server hello的个数统计一直是0

**Comment by Macr0phag3** [comment]
@cmh14 
1. 颜色的问题，你的 os 与终端类型是哪个？bash？zsh？
2. 这个已经修复了
3. 这个我这边是正常的，需要你提供一下例子：
![image](https://user-images.githubusercontent.com/20874963/92573417-58722000-f2b8-11ea-9791-f01eb0b399b0.png)

**Comment by cmh14** [comment]
您好，方便邮箱交流吗，github我不知道怎么上传截图的照片

**Comment by Macr0phag3** [comment]
@cmh14 你截图之后，在编辑框里直接粘贴就行

**Comment by Macr0phag3** [comment]
@cmh14 如果还是不会的话就用邮箱吧。主要是我们在 issue 里讨论的内容能直接给其他人作参考，比较好

**Comment by cmh14** [comment]
这个是直接运行的结果，我操作系统是win10，一开始尝试用ubuntu，但是报字符串错误就先用win10试一下
![image](https://user-images.githubusercontent.com/23030627/92573685-b9015d00-f2b8-11ea-9e22-8dac65d85ff8.png)
这个是terminal输出的结果
![image](https://user-images.githubusercontent.com/23030627/92573893-fb2a9e80-f2b8-11ea-9e00-d3a483327095.png)
可以看到有client和server相关的信息，但是统计为0
![image](https://user-images.githubusercontent.com/23030627/92574240-6e341500-f2b9-11ea-9b07-f746c5f4c412.png)

**Comment by Macr0phag3** [comment]
有点奇怪，terminal 是什么？cmd.exe？还是 powershell？

**Comment by Macr0phag3** [comment]
我好像知道哪有问题了，你这个是不是在 pycharm 里的 terminal？
用系统的终端试一下吧

**Comment by cmh14** [comment]
我不太知道pycharm的terminal用的是哪个命令行，但是我用anaconda的powershell也是这个结果
![image](https://user-images.githubusercontent.com/23030627/92574941-54df9880-f2ba-11ea-9ff5-9a47913afb4f.png)
顺便我下午还试了下在线功能，会提取一到两个握手之后就报错了，报错信息就类似上面那个截图

**Comment by cmh14** [comment]
cmd.exe和powershell结果都是一样的，都没办法正确显示颜色信息

**Comment by Macr0phag3** [comment]
你更新一下代码，然后再试一下颜色功能是否正常

**Comment by cmh14** [comment]
我去，正常了，大佬nb啊

**Comment by cmh14** [comment]
您好，这个监听端口的在线模式的问题，都是运行了几秒钟之后报错了，
![image](https://user-images.githubusercontent.com/23030627/92576978-b99bf280-f2bc-11ea-92a5-072efde2f461.png)

**Comment by Macr0phag3** [comment]
这个倒是好修复，但是我比较好奇是什么数据包引起了这个报错。

**Comment by Macr0phag3** [comment]
哈喽，请更新一下代码，然后再次运行。如果遇到这个错误，会自动生成一个 `debug.pcap`，里面会保存导致错误的那个数据包，然后这个数据包发我，我这边调试一下。发邮箱吧：macr0phag3@qq.com
@cmh14

**Comment by Macr0phag3** [comment]
@cmh14 

解决了。原因是你这个 TLS 是走 IPv6 的。多谢协助调试，现在应该没问题了。

顺便问一下，现在还有

> 还有个更加奇怪的问题，命令行中Client和Server hello的消息都可以正常打印，但是最终那个Client 和Server hello的个数统计一直是0

这个问题吗

**Comment by cmh14** [comment]
读取本地pcap文件的模式下还有，使用-i在线已经正常了好像

**Comment by cmh14** [comment]
![image](https://user-images.githubusercontent.com/23030627/92588547-bd834100-f2cb-11ea-8b43-778d455bb158.png)

**Comment by Macr0phag3** [comment]
@cmh14 
试一下最新的代码，应该已经修复了。

**Comment by cmh14** [comment]
都以解决，麻烦大佬一天了，非常感谢
