### ISSUE TITLE
offline 模式疑问

### ISSUE THREAD

**Issue by leezp** [Macr0phag3/ja3box#3]
请问离线模式下，用>python3 ja3box.py -f test.pcap 为何不显示指纹，怎样才能输出指纹

```
 ________
[__,.,--\\ __     ______
   | |    / \\   |___ //
   | |   / _ \\    |_ \\
 ._| |  / ___ \\  ___) ||  toolbox
 \__// /_//  \_\\|____//   v2.0

*] mode: offline
*] filename: 1111.pcap

*] BPF: None
*] output filename: stdout
*] output as json: False
*] save raw pcap: False

+] all packets: 99; client hello: 0; server hello: 0; in 0.1s

*] goodbye~~
```

**Comment by Macr0phag3** [comment]
`all packets: 99; client hello: 0; server hello: 0; in 0.1s`

这一行表明，你的 pcap 里有 99 个数据包，但是没有 TLS/SSL 类型的握手阶段的数据包

@leezp

**Comment by leezp** [comment]
[tls_online.zip](https://github.com/Macr0phag3/ja3box/files/5201059/tls_online.zip)

![image](https://user-images.githubusercontent.com/16287528/92719034-30a4ba00-f395-11ea-8cc0-6e8e13851886.png)

这个包是tls，您可以试下

**Comment by Macr0phag3** [comment]
看了一下，scapy 没认出来这个是 tls 的 ClientHello...

**wireshark：**
![image](https://user-images.githubusercontent.com/20874963/92719767-3cdd4700-f396-11ea-8273-bf248c964f71.png)

**scapy：**
![image](https://user-images.githubusercontent.com/20874963/92719797-48c90900-f396-11ea-899d-806ae07da298.png)

有点奇怪，我抽时间找一下解决方案

**Comment by Macr0phag3** [comment]
应该已经修复了: 6afd312b770aaac50e274886c8e7e6546791cee8，你再试一下吧，用最新版的代码
@leezp

**Comment by leezp** [comment]
good! 
@Macr0phag3 大佬，留个邮箱，加个w，讨论下恶意加密流量监控
