### ISSUE TITLE
Pure ja3 

### ISSUE THREAD

**Issue by ShindinSA** [Macr0phag3/ja3box#5]
Hello
Thx for this nice code)
I would like to know if it is possible to get pure ja3, not ja3s in online mode?

**Comment by Macr0phag3** [comment]
Done :)

https://github.com/Macr0phag3/ja3box/commit/a491e3fa0d663fa3d277a6959599ce1bca39099a

**Comment by ShindinSA** [comment]
Thank you)
Сan you explain something to me if it's not complicated?)
When checking through ja3er, my ja3 differs from the ja3 received through the script by several values
This by script : 771,10794-4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,31354-0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513-64250-21,27242-29-23-24,0

This by ja3er: 771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,29-23-24,0

Where do these extra and non-constant values ​​come from and is it possible to get rid of them without resorting to regular expressions?

**Comment by Macr0phag3** [comment]
What is ja3er?

**Comment by ShindinSA** [comment]
https://ja3er.com/

**Comment by Macr0phag3** [comment]
ok, could you share your pcaps?

**Comment by Macr0phag3** [comment]
oh...you mean when you visit [ja3er](https://ja3er.com/), it will show your ja3?

**Comment by ShindinSA** [comment]
Yes)
And it's static

**Comment by Macr0phag3** [comment]
i can not reproduce it by curl, in my cloud server

![image](https://user-images.githubusercontent.com/20874963/150752152-840c296a-6b22-46b1-a18f-6f5960d8058d.png)

**Comment by Macr0phag3** [comment]
i can not visit ja3er by chrome for GFW... and add proxy will bypass ja3box, will try again later

**Comment by ShindinSA** [comment]
Maybe it's because the script is running on a windows system
This is my pcap file
[123.zip](https://github.com/Macr0phag3/ja3box/files/7924161/123.zip)
And because of these values ​​md5 is always different

**Comment by Macr0phag3** [comment]
there is no host for ja3er.com

your pcap has something went wrong

**Comment by ShindinSA** [comment]
[new.zip](https://github.com/Macr0phag3/ja3box/files/7924233/new.zip)
Maybe this?
![test](https://user-images.githubusercontent.com/33894487/150755334-5b435cc3-a8a0-48a4-b1bd-57e636df1bac.png)

**Comment by Macr0phag3** [comment]
there is no host for ja3er.com, too

**Comment by Macr0phag3** [comment]
maybe you can try this
https://github.com/salesforce/ja3/tree/master/python
but it has no online mode

**Comment by Macr0phag3** [comment]
you need capture a pcap contains ja3er.com

**Comment by ShindinSA** [comment]
[new2.zip](https://github.com/Macr0phag3/ja3box/files/7924339/new2.zip)
Sorry, my bad
> there is no host for ja3er.com, too

**Comment by Macr0phag3** [comment]
ok, i will fix it out, it may take some time...
=(

**Comment by ShindinSA** [comment]
Thank you very match)

**Comment by Macr0phag3** [comment]
could you post the full ja3 in ja3ers?

**Comment by ShindinSA** [comment]
771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,29-23-24,0

**Comment by Macr0phag3** [comment]
![image](https://user-images.githubusercontent.com/20874963/150771011-9d5cd925-3e44-4b35-b775-1fdc185dfb3f.png)

ja3box and wireshark have the same result of this pcap, ja3ers might make a mistake.

**Comment by ShindinSA** [comment]
Maybe
This is what i got on wireshark
![002](https://user-images.githubusercontent.com/33894487/150775489-8b8d988b-3bdc-40c9-988b-0679dde97ca3.png)
On this script
![001](https://user-images.githubusercontent.com/33894487/150775558-bc41dfc9-0a6c-4efc-85c1-931f3fdee8fc.png)
And on ja3er open source code
![003](https://user-images.githubusercontent.com/33894487/150775666-0729aed7-4b9b-43f6-bff2-8a51184d0e1a.png)

Maybe I don’t understand something, but ja3 should be the same in all connections, but here it is immediately different for the same IP addresses (but in wireshark it both the same)
![004](https://user-images.githubusercontent.com/33894487/150776302-0fdcfc40-a5b3-4349-ad75-bef5774ca811.png)

**Comment by Macr0phag3** [comment]
my wireshark(macOS) shows two different results

![image](https://user-images.githubusercontent.com/20874963/150781037-b9016925-f8af-4274-bb42-175fd0b50a68.png)

![image](https://user-images.githubusercontent.com/20874963/150781064-11d03229-e0fc-418e-a264-e057dc69e1de.png)

**Comment by Macr0phag3** [comment]
ok, I figured it out.

The value of [GREASE](https://tools.ietf.org/html/draft-ietf-tls-grease-02) in ciphers or extensions **may** need to be removed. So I add two new fields: `ja3(s)_no_grease` and `md5_no_grease`. You can clone the latest code and have a try.

**but I doubt whether these GREASE should be deleted.**


![image](https://user-images.githubusercontent.com/20874963/150906587-0f900b6d-6726-4822-8062-7eb05e537d0c.png)

**Comment by ShindinSA** [comment]
Thanks a lot)
This is exactly what I needed)
